### PR TITLE
Add convert_to_utf8 script with semi-intelligent encoding checking

### LINKED ISSUE #2: Risk of converting non-Windows 1251-encoded files?
In https://github.com/writecrow/text_processing/blob/master/conversion/cp1251_to_utf8.py, as I understand it, this will always open a file with Windows 1251 character encoding (even if that file is of a different character encoding), and will write it to UTF8. 

- Does this pose the risk of over-converting characters?
- Would detecting the encoding first (using something like [chardet](https://pypi.python.org/pypi/chardet)) be a sensible precaution to add?

### PR DESCRIPTION
**Pull request by markfullmer**
## Purpose
This is meant to resolve #2 , by providing a bit more coverage on encoding conversion. Specifically:
- Instead of just trying to open files as cp1251, it checks the character encoding, then tries to open the file with that encoding
- Allows for converting a directory of files recursively, or a single file, via arguments passed to the script
- Allows for overwriting existing files or writing to an `output` directory

## Testing steps
1. Review the [README](https://github.com/writecrow/text_processing/blob/c80a015ac4747b63c4b347e0881ae8118cddd4b3/conversion/convert_to_utf8/README.md) for thoroughness & clarity.
2. From the `convert_to_utf8` directory, run `file --mime-encoding test-data/*.txt` . You should get output verifying the variegated encoding types in the test data:

```
test-data/ascii-1.txt:        us-ascii
test-data/ascii-2.txt:        us-ascii
test-data/iso08859-1.txt:     iso-8859-1
test-data/utf-32.txt:         binary
test-data/utf-8-1.txt:        utf-8
test-data/utf16-2.txt:        utf-16be
test-data/utf16le.txt:        utf-16le
test-data/windows-1251.txt:   unknown-8bit
test-data/windows-1252-1.txt: iso-8859-1
test-data/windows-1252-2.txt: unknown-8bit
test-data/windows-1254.txt:   iso-8859-1
test-data/windows-1256.txt:   iso-8859-1
```

3. `python3 convert_to_utf8.py --directory=test-data`. Verify all test files show conversion confirmation messages:

```
test-data/.DS_Store converted from cp1252
test-data/ascii-1.txt converted from ascii
test-data/ascii-2.txt converted from ascii
test-data/iso08859-1.txt converted from latin_1
test-data/utf-32.txt converted from utf_32
test-data/utf-8-1.txt already encoded in utf-8
test-data/utf16-2.txt converted from utf-16
test-data/utf16le.txt converted from utf-16
test-data/windows-1251.txt converted from windows-1251
test-data/windows-1252-1.txt converted from latin_1
test-data/windows-1252-2.txt converted from cp1252
test-data/windows-1254.txt converted from latin_1
test-data/windows-1256.txt converted from cp1256
```

4. `file --mime-encoding output/test-data/*.txt`. Verify all files have either `ascii` or `utf-8` encoding mime types:

```
output/test-data/ascii-1.txt:        us-ascii
output/test-data/ascii-2.txt:        us-ascii
output/test-data/iso08859-1.txt:     utf-8
output/test-data/utf-32.txt:         us-ascii
output/test-data/utf-8-1.txt:        utf-8
output/test-data/utf16-2.txt:        us-ascii
output/test-data/utf16le.txt:        utf-8
output/test-data/windows-1251.txt:   utf-8
output/test-data/windows-1252-1.txt: utf-8
output/test-data/windows-1252-2.txt: utf-8
output/test-data/windows-1254.txt:   utf-8
output/test-data/windows-1256.txt:   utf-8
```

### CODE REVIEW

**Comment by markfullmer** [comment]
@picoral & @Niknakflak , I'm initially just looking for feedback on whether this seems like a sensible approach to a "semi-intelligent" conversion script. Obviously, we'd want to fill out the types of encoding this can handle; I've also written it with the thought of chained script execution in mind, so if you have any thoughts about that, to, that's welcome :)

**Review by NikKirstein — APPROVED** [review]
Very useful, I need to do a similar thing for my own scripts that allows them to be used for a single file, a directory, or directories in directories.

**Comment by NikKirstein** [comment]
Is there a way to get this to work for directories of directories filled with files?

**Comment by markfullmer** [comment]
>  I need to do a similar thing for my own scripts that allows them to be used for a single file, a directory, or directories in directories.

Thanks for the feedback, @NikKirstein . I wonder if it would be useful to add a generic "General Purpose Input Output" script that only defines the wrapper stuff for being able to read from file/directory & write/overwrite. Then, that wrapper could be used with any specific scripts for text processing...

**Comment by markfullmer** [comment]
> Is there a way to get this to work for directories of directories filled with files?

I thought I'd tested it with recursive directories & it worked fine. But maybe I only tested 1-level deep? I'll review. I definitely agree that, ideally, we would want this to infinitely recurse into directories.

**Comment by NikKirstein** [comment]
Maybe you did? I couldn't figure out just how to make it work like that if so.  The wrapper sounds like a good idea.  Infinite recursion is a must since it is multiple layers deep when I have to apply scripts to a directory that has directories in it, that each has more directories in it, that has files in those.  I've had to run an unzipping script, UTF-8 converter and text-processor on this same set of files and the amount of folder hopping is quite alot.

**Comment by markfullmer** [comment]
@NikKirstein , locally, I rearranged the `test-data` directory to have 2 levels deep of files & ran the script passing that as the directory parameter. It seems to have recursed fine. Can you try something similar & let me know what behavior you get? I would think the `os_walk()` function would work on all OSes, but maybe not?

## Directory structure
screen shot 2018-01-24 at 11 26 19 am

## Script output
screen shot 2018-01-24 at 11 22 55 am

**Comment by NikKirstein** [comment]
It does work! I even ran it from a directory above that, so the script recurred through 4 layers of folders and files.  A wrapper that functions like this would be extremely useful.  This is my lack of experience showing as currently, my scripts are hard-coded to look through directories of directories when this recursive function simply eliminates that worry all together and can apply to many scripts.

**Comment by markfullmer** [comment]
Great! I'll merge this, and open up a separate pull request for the generic GPIO wrapper. Hopefully I can get to that after work today...

**Pull request merged**
